version: '3'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-latest}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025"