version: '3'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-latest}
    ports:
      - "${PORT_GENERATOR-80}:80"
    environment:
      MAILSERVER__HOST: my-prod-mailserver
      MAILSERVER_PORT: 25