# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Virtualbox
    config.vm.box = "box-cutter/ubuntu1610"

    # Hyper-V
    # config.vm.box = "kmm/ubuntu-xenial64"
    # config.vm.provider "hyperv"

    config.vm.provision "shell", path: "provision/node.sh", privileged: true

    # Managers
    (1..1).each do |number|
        config.vm.define "m#{number}" do |node|
            node.vm.network "private_network", ip: "192.168.66.20#{number}", bridge: "en0: Wi-Fi (AirPort)"
            # node.vm.network "public_network", ip: "192.168.66.20#{number}", bridge: "external_network"
            node.vm.hostname = "m#{number}"
        end
    end

    # Workers
    (1..2).each do |number|
        config.vm.define "w#{number}" do |node|
            node.vm.network "private_network", ip: "192.168.66.21#{number}", bridge: "en0: Wi-Fi (AirPort)"
            # node.vm.network "public_network", ip: "192.168.66.21#{number}", bridge: "external_network"
            node.vm.hostname = "w#{number}"
        end
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

end
