version: '3'

services:
  generator:
    build:
      context: .
    image: timothyvandenbrande/generator:multi
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"